description: Authentication using json web token
type: x-header-schema
describedBy: 
  headers: 
    Authentication: 
      description: Authentication header containing the web token
      required: true
      example: |
        Bearer GzBxtflDl76RdiZFLujo4uNVxS7MIZXbEy6D3Tle
